# Generated by Django 6.1.1 on 2026-10-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("CANCELLED", "CANCELLED"),
                    ("COMPLETED", "COMPLETED"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
