# Generated by Django 6.1.1 on 2026-09-19 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=100)),
                ("isbn", models.CharField(max_length=10, unique=True)),
                ("author", models.CharField(max_length=100)),
                ("publisher", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FICTION", "FICTION"),
                            ("NON_FICTION", "NON_FICTION"),
                            ("SCIENCE", "SCIENCE"),
                            ("TECHNOLOGY", "TECHNOLOGY"),
                            ("ENGINEERING", "ENGINEERING"),
                            ("BUSINESS", "BUSINESS"),
                            ("HISTORY", "HISTORY"),
                            ("GEOGRAPHY", "GEOGRAPHY"),
                            ("ARTS", "ARTS"),
                            ("PHILOSOPHY", "PHILOSOPHY"),
                            ("SOCIAL_SCIENCE", "SOCIAL_SCIENCE"),
                            ("EDUCATION", "EDUCATION"),
                            ("HEALTH", "HEALTH"),
                            ("LAW", "LAW"),
                            ("CHILDREN", "CHILDREN"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ENGLISH", "ENGLISH"),
                            ("HINDI", "HINDI"),
                            ("MALAYALAM", "MALAYALAM"),
                            ("TAMIL", "TAMIL"),
                            ("TELUGU", "TELUGU"),
                            ("KANNADA", "KANNADA"),
                            ("BENGALI", "BENGALI"),
                            ("MARATHI", "MARATHI"),
                            ("FRENCH", "FRENCH"),
                            ("GERMAN", "GERMAN"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("copy_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "AVAILABLE"),
                            ("BORROWED", "BORROWED"),
                            ("RESERVED", "RESERVED"),
                            ("LOST", "LOST"),
                            ("DAMAGED", "DAMAGED"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="librarymanagement.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BorrowRecord",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("date", models.DateField(auto_now=True)),
                ("exp_return", models.DateField(blank=True, null=True)),
                ("act_return", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("ACTIVE", "ACTIVE"),
                            ("RETURNED", "RETURNED"),
                            ("LOST", "LOST"),
                            ("DAMAGED", "DAMAGED"),
                        ],
                        max_length=100,
                    ),
                ),
                ("fine_amount", models.IntegerField(default=0)),
                ("fine_amount_paid", models.IntegerField(default=0)),
                ("fine_remaining", models.IntegerField(default=0)),
                (
                    "book_copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="librarymanagement.bookcopy",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="librarymanagement.member",
                    ),
                ),
            ],
        ),
    ]
