# Generated by Django 6.1.1 on 2026-09-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0002_book_image_book_is_book_of_the_day'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookcopy',
            constraint=models.UniqueConstraint(fields=('book', 'copy_number'), name='unique_book_copy_number'),
        ),
    ]
