# Generated by Django 6.1.1 on 2026-09-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0003_bookcopy_unique_book_copy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='borrow_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('BORROW PENDING', 'BORROW PENDING'), ('RETURN PENDING', 'RETURN PENDING'), ('ACTIVE', 'ACTIVE'), ('RETURNED', 'RETURNED'), ('LOST', 'LOST'), ('DAMAGED', 'DAMAGED')], max_length=100),
        ),
    ]
