# Generated by Django 6.1.1 on 2026-10-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarymanagement", "0004_borrowrecord_borrow_fee_alter_book_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="ebook",
            field=models.FileField(blank=True, null=True, upload_to="ebooks/"),
        ),
    ]
