# Generated by Django 6.1.1 on 2026-10-04 12:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("librarymanagement", "0005_book_ebook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="ebook",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="ebook"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
