# Generated by Django 6.1.1 on 2026-10-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarymanagement", "0006_alter_book_ebook_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcopy",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "AVAILABLE"),
                    ("BORROWED", "BORROWED"),
                    ("RESERVED", "RESERVED"),
                    ("LOST", "LOST"),
                    ("DAMAGED", "DAMAGED"),
                ],
                default="AVAILABLE",
                max_length=100,
            ),
        ),
    ]
