# Generated by Django 6.1.1 on 2026-10-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarymanagement", "0007_alter_bookcopy_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="borrow_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="return_updates",
            field=models.BooleanField(default=True),
        ),
    ]
