# Generated by Django 6.1.2 on 2026-10-07 19:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0008_member_borrow_updates_member_return_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
